name: "Bug Report"
description: Create a new ticket for a bug.
title: "[BUG]:"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Write a summary of the bug here.
    validations:
      required: true
  - type: textarea
    id: recreate
    attributes:
      label: "How to reproduce?"
      description: Write, step by step, how to reproduce
      value: |
        1.
        2.
        3.
        4.
      render: bash
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Result observed
      description: Describe the result observed
      placeholder: "The result observed…"
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected result
      description: What did you expect as a result?
      placeholder: "I expected…"
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Do you want to explain something more?
      placeholder: " "
    validations:
      required: false
  - type: textarea
    id: files
    attributes:
      label: Screenshots / Files
      description: You can copy and paste or drag and drop to add files.
      placeholder: "files"
    validations:
      required: false
 - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: What is the priority of this bug? 1 means low priority and 5 means high priority.
      multiple: false
      options:
        - 1 (Low priority)
        - 2
        - 3
        - 4
        - 5 (High priority)
    validations:
      required: true